server.port=5000
server.address=0.0.0.0

spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always

myapp.security.jwt-secret=dGhpc2lzYXZlcnlsb25nYW5kc2VjdXJlc2VjcmV0a2V5Zm9yand0dG9rZW5nZW5lcmF0aW9uMTIzNDU2Nzg5MA==

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
